version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
    - "5432:5432"  
    env_file:
      - ./core/.env
    networks:
      - sa-network
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./core/.env
    command: >
        sh -c "
              python3 /app/manage.py makemigrations && 
              python3 /app/manage.py migrate &&
              python3 /app/manage.py createsuperuser --no-input &&
              python3 /app/manage.py runserver 0.0.0.0:8000           
              "
    extra_hosts:
      - "host.docker.internal:172.17.0.1"          
    depends_on:
      - db
    links: 
      - db:db
    networks:
      - sa-network


  frontend:
    restart: always
    command: npm start
    container_name: front
    build:
      context: ./frontend_react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - sa-network

networks:
  sa-network:
    driver: bridge
