version: '3.9'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
        sh -c "
              python3 /app/manage.py makemigrations && 
              python3 /app/manage.py migrate &&
              python3 /app/manage.py runserver 0.0.0.0:8000
              "
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    env_file:
      - ./core/.env
    depends_on:
      - db

  db:
    image: postgres:11.10-alpine
    env_file:
      - ./core/.env
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
